config/routes.rb
Prolearning::Application.routes.draw do

  get "dashboard/index"
  get "dashboard/batch"

  resources :courses

  resources :recording_sheets do
    resources :records
  end

  resources :departments

  devise_for :users

  root :to => 'home#index'

end

app/models/recording_sheet.rb
class RecordingSheet < ActiveRecord::Base
  belongs_to :observer, :class_name => "User"
  belongs_to :teacher, :class_name => "User"
  belongs_to :department
  belongs_to :course
  has_many :records

  attr_accessible :course_id, :interval, :number_of_students, :recorded_on, :school_year, :semester, :type_of_school, :observer_id, :teacher_id, :department_id

  validates_presence_of :course_id, :interval, :number_of_students, :recorded_on, :school_year, :semester, :type_of_school, :observer_id, :teacher_id, :department_id


  def summarize
    teacher_summary = { "P - Presenting" => 0,
                        "C - Circulating" => 0, 
                        "A - Answering" => 0,
                        "D - Discussing" => 0,
                        "R - Reading / Writing" => 0,
                        "L - Listening" => 0,
                        "O - Other" => 0 }
    student_summary = { "P - Presenting" => 0,
                        "C - Circulating" => 0, 
                        "A - Answering" => 0,
                        "D - Discussing" => 0,
                        "R - Reading / Writing" => 0,
                        "L - Listening" => 0,
                        "O - Other" => 0 }
    grouping_summary = { "i - individual / one-on-one" => 0,
                         "p - pair work"=> 0,
                         "s - small group" => 0,
                         "w - whole group" => 0, 
                         "f - fluid" => 0, 
                         "o - other"=> 0 }
    topic_summary = { :cc => 0, :rs => 0, :m => 0, :d => 0, :o => 0 }

    @records = Record.where(:recording_sheet_id => self.id)
    @records.each do |record|
      teacher_summary["P - Presenting"] += record.teacher.count 'P'
      teacher_summary["C - Circulating"] += record.teacher.count 'C'
      teacher_summary["A - Answering"] += record.teacher.count 'A'
      teacher_summary["D - Discussing"] += record.teacher.count 'D'
      teacher_summary["R - Reading / Writing"] += record.teacher.count 'R'
      teacher_summary["L - Listening"] += record.teacher.count 'L'
      teacher_summary["O - Other"] += record.teacher.count 'O'

      student_summary["P - Presenting"] += record.student.count 'P'
      student_summary["C - Circulating"] += record.student.count 'C'
      student_summary["A - Answering"] += record.student.count 'A'
      student_summary["D - Discussing"] += record.student.count 'D'
      student_summary["R - Reading / Writing"] += record.student.count 'R'
      student_summary["L - Listening"] += record.student.count 'L'
      student_summary["O - Other"] += record.student.count 'O'

      grouping_summary["i - individual / one-on-one"] += record.grouping.count 'i'
      grouping_summary["p - pair work"] += record.grouping.count 'p'
      grouping_summary["s - small group"] += record.grouping.count 's'
      grouping_summary["w - whole group"] += record.grouping.count 'w'
      grouping_summary["f - fluid"] += record.grouping.count 'f'
      grouping_summary["o - other"] += record.grouping.count 'o'

      topic_summary[:cc] += record.topic.count 'cc'
      topic_summary[:rs] += record.topic.count 'rs'
      topic_summary[:m] += record.topic.count 'm'
      topic_summary[:d] += record.topic.count 'd'
      topic_summary[:o] += record.topic.count 'o'
    end
    {
      :teacher => teacher_summary, 
      :student => student_summary, 
      :grouping => grouping_summary,
      :topic => topic_summary
    }
  end

  def self.batch(conditions=[])
    recording_sheets = scoped
    conditions.each do |name, *values|
      recording_sheets = recording_sheets.send(name, *values)
    end
    recording_sheets
  end
end

app/controllers/recording_sheets_controller.rb
class RecordingSheetsController < ApplicationController
  before_filter :authenticate_user!
  # GET /recording_sheets
  # GET /recording_sheets.json
  def index
    @recording_sheets = RecordingSheet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recording_sheets }
    end
  end

  # GET /recording_sheets/1
  # GET /recording_sheets/1.json
  def show
    @recording_sheet = RecordingSheet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recording_sheet }
    end
  end

  # GET /recording_sheets/new
  # GET /recording_sheets/new.json
  def new
    @recording_sheet = RecordingSheet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recording_sheet }
    end
  end

  # GET /recording_sheets/1/edit
  def edit
    @recording_sheet = RecordingSheet.find(params[:id])
  end

  # POST /recording_sheets
  # POST /recording_sheets.json
  def create
    @recording_sheet = RecordingSheet.new(params[:recording_sheet])
    @recording_sheet.observer_id = current_user.id

    respond_to do |format|
      if @recording_sheet.save
        format.html { redirect_to @recording_sheet, notice: 'Recording sheet was successfully created.' }
        format.json { render json: @recording_sheet, status: :created, location: @recording_sheet }
      else
        format.html { render action: "new" }
        format.json { render json: @recording_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recording_sheets/1
  # PUT /recording_sheets/1.json
  def update
    @recording_sheet = RecordingSheet.find(params[:id])

    respond_to do |format|
      if @recording_sheet.update_attributes(params[:recording_sheet])
        format.html { redirect_to @recording_sheet, notice: 'Recording sheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recording_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recording_sheets/1
  # DELETE /recording_sheets/1.json
  def destroy
    @recording_sheet = RecordingSheet.find(params[:id])
    @recording_sheet.destroy

    respond_to do |format|
      format.html { redirect_to recording_sheets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recording_sheets_helper.rb
module RecordingSheetsHelper
end

app/views/recording_sheets/_form.html.erb
<%= form_for(@recording_sheet, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.control_group :observer do |f| %>
      <%= f.label :observer, class: 'control-label' %>
      <div class="controls">
        <%= current_user.email %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :teacher do |f| %>
      <%= f.label :teacher_id, class: 'control-label' %>
      <div class="controls">
        <%= f.collection_select :teacher_id, User.where("id != ?", current_user.id), :id, :email %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :recorded_on do |f| %>
      <%= f.label :recorded_on, class: 'control-label' %>
      <div class="controls">
        <%= f.date_select :recorded_on %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :school_year do |f| %>
      <%= f.label :school_year, class: 'control-label' %>
      <div class="controls">
        <%= f.number_field :school_year %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :semester do |f| %>
      <%= f.label :semester, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :semester %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :department do |f| %>
      <%= f.label :department_id, class: 'control-label' %>
      <div class="controls">
        <%= f.collection_select :department_id, Department.all, :id, :name %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :type_of_school do |f| %>
      <%= f.label :type_of_school, class: 'control-label' %>
      <div class="controls">
        <%= f.select :type_of_school, [["IB"], ["Highschool"]]%>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :course do |f| %>
      <%= f.label :course_id, class: 'control-label' %>
      <div class="controls">
        <%= f.collection_select :course_id, Course.all, :id, :name %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :number_of_students do |f| %>
      <%= f.label :number_of_students, class: 'control-label' %>
      <div class="controls">
        <%= f.number_field :number_of_students %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :interval do |f| %>
      <%= f.label :interval, class: 'control-label' %>
      <div class="controls">
        <%= f.select :interval, [[5], [1]]%>
        <%= f.error_messages %>
      </div>
    <% end %>
  
  </div>
  
  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", recording_sheets_path, class: 'btn' %>
  </div>
<% end %>

app/views/recording_sheets/edit.html.erb
<% @title = "Editing recording_sheet" %>

<%= render 'form' %>

app/views/recording_sheets/index.html.erb
<% @title = "Listing recording_sheets" %>

<% content_for :description do %>
  <p>Edit this template in <code>app/views/RecordingSheets/index.html.erb</code>.</p>
<% end %>

<% content_for :actions do %>
  <%= link_to new_recording_sheet_path, class: 'btn btn-primary btn-large pull-right' do %>
    <%= icon_tag "plus" %> Add Recording sheet
  <% end %>
<% end %>

<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table class="table">
      <thead>
        <tr>
          <th>Observer</th>
          <th>Teacher</th>
          <th>Recorded on</th>
          <th>School year</th>
          <th>Semester</th>
          <th>Department</th>
          <th>Type of school</th>
          <th>Course</th>
          <th>Number of students</th>
          <th>Interval</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @recording_sheets.each do |recording_sheet| %>
        <tr>
          <td><%= recording_sheet.observer.email %></td>
          <td><%= recording_sheet.teacher.email %></td>
          <td><%= recording_sheet.recorded_on %></td>
          <td><%= recording_sheet.school_year %></td>
          <td><%= recording_sheet.semester %></td>
          <td><%= recording_sheet.department.name %></td>
          <td><%= recording_sheet.type_of_school %></td>
          <td><%= recording_sheet.course.name %></td>
          <td><%= recording_sheet.number_of_students %></td>
          <td><%= recording_sheet.interval %></td>
          <td class="actions">
            <%= link_to icon_tag("eye-open"), recording_sheet, rel: 'tooltip', title: 'Show' %>
            <%= link_to icon_tag("pencil"), edit_recording_sheet_path(recording_sheet), rel: 'tooltip', title: 'Edit' %>
            <%= link_to icon_tag("trash"), recording_sheet, rel: 'tooltip', title: 'Delete',
                        data: { confirm: 'Are you sure?' }, method: :delete %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->

app/views/recording_sheets/new.html.erb
<% @title = "New recording_sheet" %>

<%= render 'form' %>

app/views/recording_sheets/show.html.erb
<% javascript 'https://www.google.com/jsapi' %>
<% @title = "Recording Sheet" %>
<% if @recording_sheet.records.size > 0 %>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Teacher');
        data.addColumn('number', 'Occurrences');
        data.addRows([
          <% @recording_sheet.summarize[:teacher].each do |idx, val| %>
            ['<%= idx %>', <%= val %>],
          <% end %>
        ]);

        // Set chart options
        var options = {'title':'Teacher',
                       'width':450,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('teacher_chart'));
        chart.draw(data, options);

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Student');
        data.addColumn('number', 'Occurrences');
        data.addRows([
          <% @recording_sheet.summarize[:student].each do |idx, val| %>
            ['<%= idx %>', <%= val %>],
          <% end %>
        ]);

        // Set chart options
        var options = {'title':'Student',
                       'width':450,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('student_chart'));
        chart.draw(data, options);

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Grouping');
        data.addColumn('number', 'Occurrences');
        data.addRows([
          <% @recording_sheet.summarize[:grouping].each do |idx, val| %>
            ['<%= idx %>', <%= val %>],
          <% end %>
        ]);

        // Set chart options
        var options = {'title':'Grouping',
                       'width':450,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('grouping_chart'));
        chart.draw(data, options);

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topic');
        data.addColumn('number', 'Occurrences');
        data.addRows([
          <% @recording_sheet.summarize[:topic].each do |idx, val| %>
            ['<%= idx %>', <%= val %>],
          <% end %>
        ]);

        // Set chart options
        var options = {'title':'Topic',
                       'width':450,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('topic_chart'));
        chart.draw(data, options);
      }
    </script>
  <% end %>
<div class="form-horizontal">
  <div class="control-group">
    <label class="control-label">Observer</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.observer.email %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Teacher</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.teacher.email %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Recorded on</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.recorded_on %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">School year</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.school_year %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Semester</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.semester %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Department</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.department.name %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Type of school</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.type_of_school %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Course</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.course.name %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Number of students</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.number_of_students %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Interval</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @recording_sheet.interval %></span>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to 'Back', recording_sheets_path, class: 'btn' %>
    <%= link_to icon_tag("pencil") + ' Edit', edit_recording_sheet_path(@recording_sheet), class: 'btn btn-primary' %>
    <%= link_to icon_tag("play") + ' Start', recording_sheet_records_path(@recording_sheet), class: 'btn btn-success' %>
  </div>

  <div id="teacher_chart"></div>
  <div id="student_chart"></div>
  <div id="grouping_chart"></div>
  <div id="topic_chart"></div>
</div>