config/routes.rb
Prolearning::Application.routes.draw do

  get "dashboard/index"
  get "dashboard/batch"

  resources :courses

  resources :recording_sheets do
    resources :records
  end

  resources :departments

  devise_for :users

  root :to => 'home#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :recording_sheets
  attr_accessible :name

  validates_presence_of :name
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :authenticate_user!

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.control_group :name do |f| %>
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
  </div>
  
  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", departments_path, class: 'btn' %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<% @title = "Editing department" %>

<%= render 'form' %>

app/views/departments/index.html.erb
<% @title = "Listing departments" %>

<% content_for :description do %>
  <p>Edit this template in <code>app/views/Departments/index.html.erb</code>.</p>
<% end %>

<% content_for :actions do %>
  <%= link_to new_department_path, class: 'btn btn-primary btn-large pull-right' do %>
    <%= icon_tag "plus" %> Add Department
  <% end %>
<% end %>

<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @departments.each do |department| %>
        <tr>
          <td><%= department.name %></td>
          <td class="actions">
            <%= link_to icon_tag("eye-open"), department, rel: 'tooltip', title: 'Show' %>
            <%= link_to icon_tag("pencil"), edit_department_path(department), rel: 'tooltip', title: 'Edit' %>
            <%= link_to icon_tag("trash"), department, rel: 'tooltip', title: 'Delete',
                        data: { confirm: 'Are you sure?' }, method: :delete %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->

app/views/departments/new.html.erb
<% @title = "New department" %>

<%= render 'form' %>

app/views/departments/show.html.erb
<% @title = "Showing department" %>

<div class="form-horizontal">
  <div class="control-group">
    <label class="control-label">Name</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @department.name %></span>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to icon_tag("pencil") + ' Edit', edit_department_path(@department), class: 'btn btn-primary' %>
    <%= link_to 'Back', departments_path, class: 'btn' %>
  </div>
</div>