config/routes.rb
Prolearning::Application.routes.draw do

  get "dashboard/index"
  get "dashboard/batch"

  resources :courses

  resources :recording_sheets do
    resources :records
  end

  resources :departments

  devise_for :users

  root :to => 'home#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :recording_sheet
  attr_accessible :grouping, :minute, :notes, :student, :teacher, :topic, :recording_sheet_id

  before_save do |record|
    if record.minute % 5 == 0
      @interval_records = Record.where(:recording_sheet_id => record.recording_sheet_id).where("minute BETWEEN ? AND ?", record.minute - 4, record.minute - 1)
      @interval_records.push record
      summary = summarize @interval_records
      record.summary = summary
    end
  end

  def string
    teacher.to_s + student.to_s + grouping.to_s + topic.to_s
  end
  
  def summarize(records)
    teacher_summary = { :P => 0, :C => 0, :A => 0, :D => 0, :R => 0, :L => 0, :O => 0 }
    student_summary = { :P => 0, :C => 0, :A => 0, :D => 0, :R => 0, :L => 0, :O => 0 }
    grouping_summary = { :i => 0, :p => 0, :s => 0, :w => 0, :f => 0, :o => 0 }
    topic_summary = { :cc => 0, :rs => 0, :m => 0, :d => 0, :o => 0 }

    records.each do |record|
      unless record.teacher.empty?
        teacher_summary[:P] += record.teacher.count 'P'
        teacher_summary[:C] += record.teacher.count 'C'
        teacher_summary[:A] += record.teacher.count 'A'
        teacher_summary[:D] += record.teacher.count 'D'
        teacher_summary[:R] += record.teacher.count 'R'
        teacher_summary[:L] += record.teacher.count 'L'
        teacher_summary[:O] += record.teacher.count 'O'
      end

      unless record.student.empty?
        student_summary[:P] += record.student.count 'P'
        student_summary[:C] += record.student.count 'C'
        student_summary[:A] += record.student.count 'A'
        student_summary[:D] += record.student.count 'D'
        student_summary[:R] += record.student.count 'R'
        student_summary[:L] += record.student.count 'L'
        student_summary[:O] += record.student.count 'O'
      end

      unless record.grouping.empty?
        grouping_summary[:i] += record.grouping.count 'i'
        grouping_summary[:p] += record.grouping.count 'p'
        grouping_summary[:s] += record.grouping.count 's'
        grouping_summary[:w] += record.grouping.count 'w'
        grouping_summary[:f] += record.grouping.count 'f'
        grouping_summary[:o] += record.grouping.count 'o'
      end

      unless record.topic.empty?
        topic_summary[:cc] += record.topic.count 'cc'
        topic_summary[:rs] += record.topic.count 'rs'
        topic_summary[:m] += record.topic.count 'm'
        topic_summary[:d] += record.topic.count 'd'
        topic_summary[:o] += record.topic.count 'o'
      end
    end

    #find the letter with more values and set it as summary
    summary = most_occurrent_char(teacher_summary) + most_occurrent_char(student_summary) + most_occurrent_char(grouping_summary) + most_occurrent_char(topic_summary)
  end

  def most_occurrent_char(char_count_hash)
    most_occurrent = ""
    times = 0
    char_count_hash.each do |idx, value|
      if value > 0
        if times == 0
          most_occurrent = idx.to_s
          times = value
        elsif value > times
          most_occurrent = idx.to_s
          times = value
        end
      end 
    end
    most_occurrent
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_filter :authenticate_user!
  # GET /records
  # GET /records.json
  def index
    @recording_sheet = RecordingSheet.find(params[:recording_sheet_id])
    @records = Record.where(:recording_sheet_id => @recording_sheet)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @recording_sheet = RecordingSheet.find(params[:recording_sheet_id])
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @recording_sheet = RecordingSheet.find(params[:recording_sheet_id])
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @recording_sheet = RecordingSheet.find(params[:recording_sheet_id])
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @recording_sheet = RecordingSheet.find(params[:recording_sheet_id])
    @record = Record.new(params[:record])
    @record.recording_sheet_id = @recording_sheet.id

    respond_to do |format|
      if @record.save
        format.html { redirect_to recording_sheet_record_path(@recording_sheet, @record), notice: 'Record was successfully created.' }
        format.json { render json: @record, status: :created, location: recording_sheet_record_path(@recording_sheet, @record) }
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @recording_sheet = RecordingSheet.find(params[:recording_sheet_id])
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to recording_sheet_record_path(@recording_sheet, @record), notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @recording_sheet = RecordingSheet.find(params[:recording_sheet_id])
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to recording_sheet_records_path(@recording_sheet) }
      format.json { head :no_content }
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for([@recording_sheet, @record], html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.control_group :minute do |f| %>
      <%= f.label :minute, class: 'control-label' %>
      <div class="controls">
        <%= f.number_field :minute %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :teacher do |f| %>
      <%= f.label :teacher, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :teacher %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :student do |f| %>
      <%= f.label :student, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :student %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :grouping do |f| %>
      <%= f.label :grouping, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :grouping %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :topic do |f| %>
      <%= f.label :topic, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :topic %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
    <%= f.control_group :notes do |f| %>
      <%= f.label :notes, class: 'control-label' %>
      <div class="controls">
        <%= f.text_area :notes %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
  </div>
  
  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", recording_sheet_records_path, class: 'btn' %>
  </div>
<% end %>

app/views/records/edit.html.erb
<% @title = "Editing record" %>

<%= render 'form' %>

app/views/records/index.html.erb
<% @title = "Listing records" %>

<% content_for :description do %>
  <!--  <p>Edit this template in <code>app/views/Records/index.html.erb</code>.</p> -->
<% end %>

<style type="text/css">
  .time {
    font-weight: bold;
    font-size: 50px;
  }
  .help-block {
    display: none;
  }
</style>

<div id="progress-bar" class="progress progress-info
     progress-striped active">
  <div class="bar"
       style="width: 0%;"></div>
</div>
  <div class="form-inputs">
    <div class="row-fluid">
      <div class="span2">
            <h1>Timer</h1>
            </br>
            <span class="time">
              <span class="minute">0</span>'
              <span class="second">0</span>"
            </span>
            <button id="start-stopwatch" class="btn btn-danger"><i class="icon-play-circle"></i> Record</button>
            <button id="pause-stopwatch" class="btn btn" style="display:none;"><i class="icon-pause"></i> Pause</button>
            <br/>
            <br/>
            <button id="show-info" class="btn btn-info"><i class="icon-info-sign"></i> Info</button>
      </div>
      <div class="span10">
        <div class="row-fluid actionable">
          <div id="teacher-selector" class="span3">
            <h1>Teacher</h1>
            <a class="btn btn-small">P</a>
            <a class="btn btn-small">C</a>
            <a class="btn btn-small">A</a>
            <a class="btn btn-small">D</a>
            <a class="btn btn-small">R</a>
            <a class="btn btn-small">L</a>
            <a class="btn btn-small">O</a>
              <p class="help-block">
              P - Presenting / Explaining</br>
              C - Circulating</br>
              A - Answering</br>
              D - Discussing</br>
              R - Reading / Writing</br>
              L - Listening</br>
              O - Other</br>
              </p>
          </div>
          <div id="student-selector" class="span3">
            <h1>Student</h1>
            <a class="btn btn-small">P</a>
            <a class="btn btn-small">C</a>
            <a class="btn btn-small">A</a>
            <a class="btn btn-small">D</a>
            <a class="btn btn-small">R</a>
            <a class="btn btn-small">L</a>
            <a class="btn btn-small">O</a>
              <p class="help-block">
              P - Presenting / Explaining</br>
              C - Circulating</br>
              A - Answering</br>
              D - Discussing</br>
              R - Reading / Writing</br>
              L - Listening</br>
              O - Other</br>
              </p>
          </div>
          <div id="grouping-selector" class="span3">
            <h1>Grouping</h1>
            <a class="btn btn-small">i</a>
            <a class="btn btn-small">p</a>
            <a class="btn btn-small">s</a>
            <a class="btn btn-small">w</a>
            <a class="btn btn-small">f</a>
            <a class="btn btn-small">o</a>
              <p class="help-block">
              i - individual / one-on-one</br>
              p - pair work</br>
              s - small group</br>
              w - whole group</br>
              f - fluid</br>
              o - other</br>
              </p>
          </div>
          <div id="topic-selector" class="span3">
            <h1>Topic</h1>
            <a class="btn btn-small">cc</a>
            <a class="btn btn-small">rs</a>
            <a class="btn btn-small">m</a>
            <a class="btn btn-small">d</a>
            <a class="btn btn-small">o</a>
              <p class="help-block">
              i - individual / one-on-one</br>
              p - pair work</br>
              s - small group</br>
              w - whole group</br>
              f - fluid</br>
              o - other</br>
              </p>
          </div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <br/><br/>
        <textarea class="field span12" id="notes" rows="6" placeholder="Notes"></textarea>
      </div>
    </div>
  </div>
  
    <%= link_to "Back", recording_sheet_path(params[:recording_sheet_id]), class: 'btn' %>

<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table id="results" class="table">
      <thead>
        <tr>
          <th>Minute</th>
          <th>String</th>
          <th>Notes</th>
          <th>Summary</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @records.each do |record| %>
        <tr>
          <td><%= record.minute %></td>
          <td><%= record.string %></td>
          <td><%= record.notes %></td>
          <td><%= record.summary %></td>
          <td class="actions">
            <%= link_to icon_tag("eye-open"), recording_sheet_record_path(record.recording_sheet, record), rel: 'tooltip', title: 'Show' %>
            <%= link_to icon_tag("pencil"), edit_recording_sheet_record_path(record.recording_sheet, record), rel: 'tooltip', title: 'Edit' %>
            <%= link_to icon_tag("trash"), recording_sheet_record_path(record.recording_sheet, record), rel: 'tooltip', title: 'Delete',
                        data: { confirm: 'Are you sure?' }, method: :delete %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->

app/views/records/new.html.erb
<% @title = "New record" %>

<%= render 'form' %>

app/views/records/show.html.erb
<% @title = "Showing record" %>

<div class="form-horizontal">
  <div class="control-group">
    <label class="control-label">Minute</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @record.minute %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Teacher</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @record.teacher %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Student</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @record.student %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Grouping</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @record.grouping %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Topic</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @record.topic %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Notes</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @record.notes %></span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">Recording sheet</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @record.recording_sheet %></span>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to icon_tag("pencil") + ' Edit', edit_recording_sheet_record_path(@record.recording_sheet, @record), class: 'btn btn-primary' %>
    <%= link_to 'Back', recording_sheet_records_path, class: 'btn' %>
  </div>
</div>