config/routes.rb
Prolearning::Application.routes.draw do

  get "dashboard/index"
  get "dashboard/batch"

  resources :courses

  resources :recording_sheets do
    resources :records
  end

  resources :departments

  devise_for :users

  root :to => 'home#index'

end

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, app_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>
    
    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>
    
    <%= yield :head %>
  </head>
  <body>
    <header>
      <%= render "layouts/navbar" %>
      <%= yield :header %>
      <hr />
    </header>
    
    <%= yield :banner %>

    <div id="main">
      <div class="container">
        <%= render "layouts/flashes" %>

        <%= yield %>
      </div> <!-- /.container -->
    </div> <!-- /#main -->
    
    <%= render "layouts/footer" %>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>

  </body>
<% end %>

app/views/layouts/_flashes.html.erb
<% if alert %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "remove" %> <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-warning">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "info-sign" %> <%= notice %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p class="pull-right">
      <%= link_to "Home", root_path %>
      &middot;
      <%= link_to "About", "#" %>
      &middot;
      <%= link_to "Contact Us", "#" %>
      &middot;
      <%= link_to "Terms", "#" %>
      &middot;
      <%= link_to "Privacy", "#" %>
    </p>
    <p>&copy; <%= Date.today.year %> <%= app_name %>. All rights reserved.</p>
    <p>Theme by <%= link_to "Dresssed", "http://dresssed.com" %>.</p>
  </div> <!-- /.container -->
</footer>

app/views/layouts/_navbar.html.erb
<%# Top navigation bar containing the main menu of your app. %>
<div class="navbar navbar-fixed-top">
  <!-- TIP: to unfix the navbar:
    1. remove the 'navbar-fixed-top' class here and
    2. add the 'static-navbar' class to your body tag. -->
  <div class="navbar-inner">
    <div class="container">

      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- Le logo -->
      <a class="brand" href="<%= root_path %>"><%= app_name %></a>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse">
      <% if user_signed_in? %>
        <ul class="nav">
          <%= activatable_li_tag_with_link "Home", root_path %>
          <%= activatable_li_tag_with_link "Departments", departments_path %>
          <%= activatable_li_tag_with_link "Courses", courses_path %>
          <%= activatable_li_tag_with_link "Dashboard", dashboard_index_path %>
        </ul> <!-- /.nav -->
      <% end %>
        
        <%= yield :navbar %>
      </div> <!-- /.nav-collapse -->

    </div> <!-- /.container -->
  </div> <!-- /.navbar-inner -->
</div> <!-- /.navbar -->

app/views/layouts/_user_nav.html.erb
<%# Links for current user. %>
<div class="navbar-text pull-right">

  <% if user_signed_in? %>
    <%= icon_tag "user" %> Welcome, <strong><%= current_user.email %></strong>
    <span class="divider">|</span>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path)  %>  
  <% end %>

</div>

app/views/layouts/application.html.erb
<% content_for :navbar, render("layouts/user_nav") %>

<%= render :layout => "layouts/base" do %>
  <div class="page-header">
    <div class="row">
      <div class="span7">
        <h2><%= @title %></h2>
        <%= yield :description %>
      </div>
      <div class="span2">
        <%= yield :actions %>
      </div>
    </div>
  </div><!-- /.page-header -->

  <div class="row">
    <div id="content" class="span12">
      <%= yield %>            
    </div> <!-- /#content -->

    <!--
    <div id="sidebar" class="span3">
      <h6>Menu</h6>
      <p></p>

      <ul class="nav nav-tabs nav-stacked nav-caret-left">
        <%= activatable_li_tag_with_link "Sub menu", nil %>
        <%= activatable_li_tag_with_link "Another menu", "#" %>
        <%= activatable_li_tag_with_link "A last one", "#" %>
      </ul>
    </div> <!-- /#sidebar -->
  </div> <!-- /.row -->
<% end %>

app/views/layouts/home.html.erb
<% content_for :navbar do %>
  <%= form_tag "?", :class => "navbar-search pull-right" do %>
    <%= text_field_tag :query, params[:query], :class => "search-query" %>
  <% end %>
<% end %>

<%= render :layout => "layouts/base" do %>
  <%= yield %>
<% end %>